# Generated by Django 6.0.1 on 2026-04-20 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_swap_photo_url_to_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="primary_clinic",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_vet_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_vet_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="UserSpecialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinic_name", models.CharField(blank=True, max_length=255)),
                ("vet_name", models.CharField(max_length=255)),
                ("vet_email", models.EmailField(blank=True, max_length=254)),
                ("specialty", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
