services:
  db:
    image: postgres:16
    container_name: petcare_postgres
    environment:
      POSTGRES_DB: petcare
      POSTGRES_USER: petcare_user
      POSTGRES_PASSWORD: petcare_password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: petcare
      DB_USER: petcare_user
      DB_PASSWORD: petcare_password
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata: