# Generated by Django 6.0.1 on 2026-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="age_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pet",
            name="spayed_neutered",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
