# Generated by Django 6.0.1 on 2026-04-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_petinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
            ),
        ),
    ]
