# Generated by Django 6.0.1 on 2026-04-06 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_alter_petinvite_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="age_years",
        ),
    ]
