# Generated by Django 6.0.1 on 2026-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_remove_pet_age_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="share_code",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=12, null=True
            ),
        ),
    ]
