# Generated by Django 6.0.1 on 2026-04-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0008_backfill_pet_share_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="share_code",
            field=models.CharField(
                db_index=True, editable=False, max_length=12, unique=True
            ),
        ),
    ]
