# Generated by Django 6.0.1 on 2026-03-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petassessment',
            name='significantly_challenged',
            field=models.BooleanField(default=False),
        ),
    ]
