# Generated by Django 6.0.1 on 2026-03-02 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0002_pet_age_years_pet_spayed_neutered"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkin_date", models.DateField(db_index=True)),
                (
                    "day_rating",
                    models.CharField(
                        choices=[
                            ("good", "Good"),
                            ("neutral", "Neutral"),
                            ("bad", "Bad"),
                        ],
                        default="neutral",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_checkins",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-checkin_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pet", "checkin_date"],
                        name="pet_calenda_pet_id_b6dacd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pet", "author", "checkin_date"),
                        name="uniq_checkin_per_pet_author_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("text", models.TextField(blank=True, default="")),
                ("photo_url", models.URLField(blank=True, default="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("shared", "Shared"), ("private", "Private")],
                        db_index=True,
                        default="shared",
                        max_length=16,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("food", "Food"),
                            ("sleep", "Sleep"),
                            ("med", "Medication"),
                            ("symptoms", "Symptoms"),
                        ],
                        db_index=True,
                        default="",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_time", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pet", "entry_time"],
                        name="pet_calenda_pet_id_4bf715_idx",
                    ),
                    models.Index(
                        fields=["visibility", "entry_time"],
                        name="pet_calenda_visibil_ca138d_idx",
                    ),
                ],
            },
        ),
    ]
