# Generated by Django 6.0.1 on 2026-03-02 04:32

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_calendar", "0001_initial"),
        ("pets", "0002_pet_age_years_pet_spayed_neutered"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={"ordering": ["-entry_date", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="pet_calenda_pet_id_4bf715_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="pet_calenda_visibil_ca138d_idx",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["pet", "entry_date"], name="pet_calenda_pet_id_b0da0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["visibility", "entry_date"],
                name="pet_calenda_visibil_878b48_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="entry_time",
        ),
    ]
