# Generated by Django 6.0.1 on 2026-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_calendar", "0002_alter_journalentry_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalentry",
            name="tag",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
    ]
