# Generated by Django 6.0.1 on 2026-03-30 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet_calendar", "0003_alter_journalentry_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="tag",
        ),
        migrations.CreateModel(
            name="JournalTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="journal_entries", to="pet_calendar.journaltag"
            ),
        ),
        migrations.AddConstraint(
            model_name="journaltag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_journal_tag_per_user"
            ),
        ),
    ]
