# Generated by Django 6.0.1 on 2026-03-30 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pet_calendar",
            "0004_remove_journalentry_tag_journaltag_journalentry_tags_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="journaltag",
            name="color",
            field=models.CharField(
                default="#917869",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Color must be a valid hex code like #917869.",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="entry_date",
            field=models.DateField(db_index=True),
        ),
    ]
