# Generated by Django 6.0.1 on 2026-03-23 19:15

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0003_pet_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('liquid', 'Liquid'), ('injection', 'Injection'), ('topical', 'Topical'), ('other', 'Other')], max_length=50)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('topical', 'Topical'), ('ophthalmic', 'Ophthalmic'), ('otic', 'Otic'), ('inhaled', 'Inhaled'), ('injectable', 'Injectable'), ('other', 'Other')], max_length=50)),
                ('strength_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('strength_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('concentration_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('concentration_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('dose_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dose_unit', models.CharField(max_length=50)),
                ('sig_text', models.TextField()),
                ('reason_for_use', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('completed', 'Completed')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('as_needed', models.BooleanField(default=False)),
                ('max_doses_per_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('with_food', models.BooleanField(blank=True, null=True)),
                ('prescribing_vet_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reminders_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pets.pet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('fixed_times', 'Fixed Times'), ('interval', 'Interval'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=20)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), blank=True, help_text='e.g. ["mon","wed","fri"]', null=True)),
                ('interval_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medication')),
            ],
        ),
        migrations.AddIndex(
            model_name='medication',
            index=models.Index(fields=['pet'], name='medications_pet_id_21ca35_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationschedule',
            index=models.Index(fields=['medication'], name='medications_medicat_e5a66b_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('schedule_type', 'interval'), _negated=True), ('interval_hours__isnull', False), _connector='OR'), name='ck_interval_requires_interval_hours'),
        ),
        migrations.AddConstraint(
            model_name='medicationschedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('schedule_type', 'fixed_times'), _negated=True), ('time_of_day__isnull', False), _connector='OR'), name='ck_fixed_times_requires_time_of_day'),
        ),
    ]
