# Generated by Django 6.0.1 on 2026-04-05 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity_unit', models.CharField(max_length=50)),
                ('quantity_remaining', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dose_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dose_unit', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('refills_authorized', models.PositiveSmallIntegerField(default=0)),
                ('refills_used', models.PositiveSmallIntegerField(default=0)),
                ('prescribing_vet_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medications.medication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medication'], name='medications_medicat_80add3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_total__gt', 0)), name='ck_prescription_quantity_total_positive')],
            },
        ),
    ]
