# Generated by Django 6.0.1 on 2026-04-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_medicationprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='form_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
