# Generated by Django 6.0.1 on 2026-04-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_add_medication_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
