# Generated by Django 6.0.1 on 2026-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_add_medication_log_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
